name: Test build Docker image

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: bl0m1/actions/docker-lint@docker-lint
  build:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/master'
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag bl0m1/rclonemove:latest
  buildandpush:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag bl0m1/rclonemove:latest
      - name: Login to dockerhub
        run: docker login -u bl0m1 -p ${{ secrets.DOCKER_PASS }}
      - name: Push the Docker image
        run: docker push bl0m1/rclonemove:latest
