name: Test build Docker image

on: 
  push:
    branches:
      - master
  pull_request:
    branches:    
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: bl0m1/actions/docker-lint@main
  buildandpush:
    runs-on: ubuntu-latest
    needs: lint
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag bl0m1/rclonemove:latest
      - name: Login to dockerhub
        run: docker login -u bl0m1 -p ${{ secrets.DOCKER_PASS }}
      - name: Push the Docker image
        run: docker push bl0m1/rclonemove:latest
